services:
  lyra:
    container_name: lyra
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - GIT_USER_EMAIL=lyra@zetk.in
      - GIT_USER_NAME="Lyra Translator Bot"
    volumes:
      - ~/.ssh/id_rsa:/home/nodeuser/.ssh/id_rsa:ro
      - ./config:/app/config